"if (Validate::isEmail($email))" it's always true
PrestaShop/ps_emailsubscription pull request #72
Opened 2020-12-31 19:02 UTC by moncef-essid

"if (Validate::isEmail($email))" it's always true, since the $email is already validated at the creation moment of the customer, so the script won't be able to achieve the rest of cases.

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Please be specific when describing the PR. <br> Every detail helps: versions, browser/server configuration, specific module/theme, etc. Feel free to add more information below this table.
| Type?         | bug fix / improvement / new feature / refacto / critical
| BC breaks?    | yes / no
| Deprecations? | yes / no
| Fixed ticket? | Fixes PrestaShop/Prestashop#{issue number here}.
| How to test?  | Please indicate how to best verify that this PR is correct.

2021-01-02 09:37 UTC, Arman-Hosseini commented
Please use the appropriate title for your PR and commit and also fill the Q&A table.

2021-01-04 08:37 UTC, PierreRambaud requested changes
Please correctly fill the pull request template :)

2021-01-15 06:27 UTC, kpodemski approved these changes

2021-01-15 08:00 UTC, PierreRambaud approved these changes

2021-01-29 16:46 UTC, khouloudbelguith commented
Hi @moncef-essid,

I found a difference between with or without PR when creating a guest customer.
Steps to reproduce the behavior

1. Go to BO > Module manager > ps_emailsubscription configuration page > Enable `Would you like to send a confirmation email after subscription?`
2. Go to FO > Add a product t the cart > continue checkout > in the Personal information step
3. Create a guest customer by selecting `Sign up for our newsletter`
4. Click on continue
5. Check email > Newsletter confirmation email is well received
6. Complete the order
7. Repeat steps from the second one (create an order with the same guest)
8. Check email > Newsletter confirmation email is well received again
![image](https://user-images.githubusercontent.com/16067358/106302909-d29c4480-6259-11eb-80e9-8afb20998a24.png)


**Without PR**, This behavior is not reproduced.

Thanks to check and feedback.

2021-04-01 17:42 UTC, sarahdib commented
Hello

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to ask te re-open if you can provide more details.

Thank you!

2021-04-01 17:42 UTC, closed without merging