Spelling error
PrestaShop/ps_emailsubscription pull request #73
Opened 2020-12-31 19:21 UTC by moncef-essid

Spelling error

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Please be specific when describing the PR. <br> Every detail helps: versions, browser/server configuration, specific module/theme, etc. Feel free to add more information below this table.
| Type?         | bug fix / improvement / new feature / refacto / critical
| BC breaks?    | yes / no
| Deprecations? | yes / no
| Fixed ticket? | Fixes PrestaShop/Prestashop#{issue number here}.
| How to test?  | Please indicate how to best verify that this PR is correct.

2021-01-04 08:41 UTC, PierreRambaud requested changes
Please correctly fill the pull request template

2021-01-15 06:26 UTC, kpodemski approved these changes

2021-01-15 14:34 UTC, PierreRambaud approved these changes

2021-01-15 14:35 UTC, merged

2021-01-15 14:35 UTC, PierreRambaud commented
Thank you @moncef-essid