copy/paste error
PrestaShop/ps_emailsubscription pull request #74
Opened 2020-12-31 19:24 UTC by moncef-essid

copy/paste error

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Please be specific when describing the PR. <br> Every detail helps: versions, browser/server configuration, specific module/theme, etc. Feel free to add more information below this table.
| Type?         | bug fix / improvement / new feature / refacto / critical
| BC breaks?    | yes / no
| Deprecations? | yes / no
| Fixed ticket? | Fixes PrestaShop/Prestashop#{issue number here}.
| How to test?  | Please indicate how to best verify that this PR is correct.

2021-01-02 09:19 UTC, Arman-Hosseini commented
Any reason?

2021-01-04 08:41 UTC, PierreRambaud requested changes
Please correctly fill the pull request template

2021-01-09 18:37 UTC, kpodemski commented
This is of course is a good change, but please follow instructions from @PierreRambaud and provide us with content of PR template. Could you do that?

2021-01-13 10:56 UTC, kpodemski requested changes

2021-01-13 10:56 UTC, kpodemski commented on ps_emailsubscription.php
> +                        'default_value' => 0,
```suggestion
                        'default_value' => 1,
```

2021-01-13 10:56 UTC, kpodemski commented on ps_emailsubscription.php
> +                        'default_value' => 0,
```suggestion
                        'default_value' => 1,
```

2021-01-13 10:58 UTC, kpodemski commented
@PierreRambaud 

you can check this PR again, I help @moncef-essid as we don't have any reply from him

2021-01-13 14:45 UTC, PierreRambaud approved these changes

2021-01-14 07:51 UTC, Progi1984 approved these changes

2021-01-26 16:24 UTC, khouloudbelguith commented
Hi @moncef-essid,

It is ok :heavy_check_mark: 
I checked with develop branch & 177x branch.
https://drive.google.com/file/d/1LtJw5krKkWmZgBraLbjVR7bZgwIArI13/view?usp=sharing

Thank you!

2021-01-26 16:41 UTC, merged

2021-01-26 16:41 UTC, Progi1984 commented
Thanks @moncef-essid & @khouloudbelguith